/**
 * Stable machine-readable error codes returned in `{ error: { code, ... } }`
 * (Section 5). The frontend and the public Developer API both branch on these,
 * so treat every value here as part of the public contract: add, don't rename.
 */
export const ErrorCode = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PASSWORD_LOGIN_UNAVAILABLE: 'PASSWORD_LOGIN_UNAVAILABLE',
  PASSWORD_RESET_INVALID: 'PASSWORD_RESET_INVALID',
  OAUTH_PROVIDER_NOT_CONFIGURED: 'OAUTH_PROVIDER_NOT_CONFIGURED',

  // Workspace
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_CONTEXT_REQUIRED: 'WORKSPACE_CONTEXT_REQUIRED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

  // Social accounts / platform OAuth (Section 6)
  PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
  PLATFORM_NOT_CONFIGURED: 'PLATFORM_NOT_CONFIGURED',
  PLATFORM_CAPABILITY_UNSUPPORTED: 'PLATFORM_CAPABILITY_UNSUPPORTED',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_EXCHANGE_FAILED: 'OAUTH_EXCHANGE_FAILED',
  OAUTH_ACCESS_DENIED: 'OAUTH_ACCESS_DENIED',
  SOCIAL_ACCOUNT_NOT_FOUND: 'SOCIAL_ACCOUNT_NOT_FOUND',
  SOCIAL_ACCOUNT_ALREADY_CONNECTED: 'SOCIAL_ACCOUNT_ALREADY_CONNECTED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  INSTAGRAM_BUSINESS_ACCOUNT_REQUIRED: 'INSTAGRAM_BUSINESS_ACCOUNT_REQUIRED',
  PINTEREST_BOARD_NOT_FOUND: 'PINTEREST_BOARD_NOT_FOUND',
  REMOTE_MEDIA_UNSAFE: 'REMOTE_MEDIA_UNSAFE',
  ENCRYPTION_NOT_CONFIGURED: 'ENCRYPTION_NOT_CONFIGURED',

  // AI providers (Section 2)
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  AI_CREDENTIAL_INVALID: 'AI_CREDENTIAL_INVALID',
  AI_MODEL_NOT_SUPPORTED: 'AI_MODEL_NOT_SUPPORTED',
  AI_REQUEST_FAILED: 'AI_REQUEST_FAILED',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  VOICE_INGESTION_CONSENT_REQUIRED: 'VOICE_INGESTION_CONSENT_REQUIRED',
  CONTENT_TYPE_NOT_READY: 'CONTENT_TYPE_NOT_READY',
  IMAGE_COUNT_MISMATCH: 'IMAGE_COUNT_MISMATCH',
  IMAGE_SOURCE_CONFLICT: 'IMAGE_SOURCE_CONFLICT',
  MEDIA_ASSET_NOT_FOUND: 'MEDIA_ASSET_NOT_FOUND',
  VIDEO_REQUIRED: 'VIDEO_REQUIRED',
  STORAGE_NOT_CONFIGURED: 'STORAGE_NOT_CONFIGURED',
  MEDIA_UPLOAD_NOT_FOUND: 'MEDIA_UPLOAD_NOT_FOUND',
  MEDIA_UPLOAD_INVALID: 'MEDIA_UPLOAD_INVALID',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_TRANSCODE_FAILED: 'MEDIA_TRANSCODE_FAILED',
  CONTENT_GOAL_REQUIRED: 'CONTENT_GOAL_REQUIRED',
  CONTENT_TOPIC_REQUIRED: 'CONTENT_TOPIC_REQUIRED',
  CONTENT_TOO_SIMILAR: 'CONTENT_TOO_SIMILAR',
  IMAGE_PROVIDER_NOT_CONFIGURED: 'IMAGE_PROVIDER_NOT_CONFIGURED',
  CONTENT_INVALID_FOR_PLATFORM: 'CONTENT_INVALID_FOR_PLATFORM',
  POST_NOT_CANCELABLE: 'POST_NOT_CANCELABLE',
  POST_NOT_PUBLISHABLE: 'POST_NOT_PUBLISHABLE',
  SCHEDULE_CONFIGURATION_INVALID: 'SCHEDULE_CONFIGURATION_INVALID',
  BRAND_URL_INVALID: 'BRAND_URL_INVALID',
  BRAND_URL_UNSAFE: 'BRAND_URL_UNSAFE',
  BRAND_RESEARCH_FAILED: 'BRAND_RESEARCH_FAILED',
  TIKTOK_RESEARCH_NOT_CONFIGURED: 'TIKTOK_RESEARCH_NOT_CONFIGURED',
  AUTOMATION_ASSETS_REQUIRED: 'AUTOMATION_ASSETS_REQUIRED',
  AUTOMATION_TIKTOK_REQUIRED: 'AUTOMATION_TIKTOK_REQUIRED',
  ENGAGEMENT_CONFIGURATION_INVALID: 'ENGAGEMENT_CONFIGURATION_INVALID',
  PUBLISHING_PROVIDER_NOT_CONFIGURED: 'PUBLISHING_PROVIDER_NOT_CONFIGURED',
  PUBLISHING_PROVIDER_CREDENTIAL_INVALID: 'PUBLISHING_PROVIDER_CREDENTIAL_INVALID',
  PUBLISHING_PROVIDER_ORGANIZATION_REQUIRED: 'PUBLISHING_PROVIDER_ORGANIZATION_REQUIRED',
  PUBLISHING_PROVIDER_CHANNEL_INVALID: 'PUBLISHING_PROVIDER_CHANNEL_INVALID',
  PUBLISHING_PROVIDER_DEFAULTS_REQUIRED: 'PUBLISHING_PROVIDER_DEFAULTS_REQUIRED',
  PUBLISHING_PROVIDER_URL_UNSAFE: 'PUBLISHING_PROVIDER_URL_UNSAFE',
  PUBLISHING_PROVIDER_RATE_LIMITED: 'PUBLISHING_PROVIDER_RATE_LIMITED',
  PUBLISHING_PROVIDER_REQUEST_FAILED: 'PUBLISHING_PROVIDER_REQUEST_FAILED',
  PUBLISHING_PROVIDER_HAS_PENDING_POSTS: 'PUBLISHING_PROVIDER_HAS_PENDING_POSTS',

  // POSTLOCK public X verification
  X_PROFILE_PROVIDER_FAILED: 'X_PROFILE_PROVIDER_FAILED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
