"use client";
import { Bot, CircleAlert, Clock3, Code2, KeyRound, MessageCircleReply, PauseCircle, Plus, ShieldCheck, Webhook, Zap, type LucideIcon } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { useWorkspace } from "@/components/app/app-shell";
import { PageHeader } from "@/components/app/page-header";
import { EmptyState } from "@/components/shared/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api";
import { formatDate, titleCase } from "@/lib/utils";

export function EngagementView(){const {workspace}=useWorkspace();const [tab,setTab]=useState<"queue"|"rules">("queue");const interactions=useQuery({queryKey:["engagement-interactions",workspace?.id],queryFn:()=>api<unknown[]>("/engagement/interactions",{},workspace?.id),enabled:!!workspace,retry:false});const rules=useQuery({queryKey:["engagement-rules",workspace?.id],queryFn:()=>api<unknown[]>("/engagement/rules",{},workspace?.id),enabled:!!workspace,retry:false});const unavailable=interactions.isError&&rules.isError;return <><PageHeader eyebrow="Conversations" title="Engagement" description="Draft thoughtful replies, keep sensitive conversations in review, and stay in control of what posts." actions={<Button disabled={unavailable}><Plus className="size-4"/>New rule</Button>}/><div className="mb-5 flex gap-2"><Button size="sm" variant={tab==="queue"?"secondary":"outline"} onClick={()=>setTab("queue")}>Review queue</Button><Button size="sm" variant={tab==="rules"?"secondary":"outline"} onClick={()=>setTab("rules")}>Automation rules</Button></div>{unavailable?<ComingSoon icon={MessageCircleReply} title="Engagement engine is ready for its backend" description="The full review queue, safety filters, approval flow, and reply limits are designed here. Configure the engagement routes to activate them."/>:<EmptyState title={tab==="queue"?"Nothing needs review":"No engagement rules"} description={tab==="queue"?"Replies that need a human decision will appear here.":"Create a rule to draft or safely publish replies."} icon={tab==="queue"?ShieldCheck:Bot}/>}</>}
export function AutomationView(){const {workspace}=useWorkspace();const status=useQuery({queryKey:["automation-status",workspace?.id],queryFn:()=>api<Record<string,unknown>>("/automation/status",{},workspace?.id),enabled:!!workspace,retry:false});const audit=useQuery({queryKey:["automation-audit",workspace?.id],queryFn:()=>api<unknown[]>("/automation/audit-log",{},workspace?.id),enabled:!!workspace,retry:false});const unavailable=status.isError&&audit.isError;const stats:Array<[LucideIcon,string,number]>=[[Zap,"Active schedules",0],[MessageCircleReply,"Active reply rules",0],[CircleAlert,"Needs attention",0]];return <><PageHeader eyebrow="Transparency" title="Automation activity" description="See what Swiply did, why it did it, and stop autonomous work in one click." actions={<Button variant="destructive" disabled={unavailable}><PauseCircle className="size-4"/>Pause all automation</Button>}/><div className="mb-6 grid gap-4 sm:grid-cols-3">{stats.map(([Icon,label,value])=><Card key={label}><CardContent className="flex items-center gap-4 pt-5"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div><p className="font-display text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div>{unavailable?<ComingSoon icon={Clock3} title="No automation events yet" description="Once the automation backend is enabled, every generated post, publish, reply, pause, and failure will appear in this audit timeline."/>:<EmptyState title="Activity will appear here" description="Every autonomous action is recorded for your review." icon={Clock3}/>}</>}
export function DeveloperView(){const {workspace}=useWorkspace();const keys=useQuery({queryKey:["developer-keys",workspace?.id],queryFn:()=>api<unknown[]>("/dev/api-keys",{},workspace?.id),enabled:!!workspace,retry:false});return <><PageHeader eyebrow="Build" title="Developer tools" description="Create scoped API keys, receive signed events, and integrate Swiply into your own workflows." actions={<Button disabled={keys.isError}><Plus className="size-4"/>Create API key</Button>}/><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><KeyRound className="size-5"/></span><Badge variant={keys.isError?"warning":"success"}>{keys.isError?"Backend pending":"Available"}</Badge></div><CardTitle className="pt-3">API keys</CardTitle><CardDescription>Issue live or test keys with the minimum scopes each integration needs.</CardDescription></CardHeader><CardContent>{keys.isError?<p className="rounded-xl bg-muted p-4 text-sm text-muted-foreground">Developer API routes are not enabled on this backend yet.</p>:<EmptyState className="min-h-36" title="No API keys" description="Secrets are shown once when created." icon={KeyRound}/>}</CardContent></Card><Card><CardHeader><span className="grid size-10 place-items-center rounded-xl bg-secondary/10 text-secondary"><Webhook className="size-5"/></span><CardTitle className="pt-3">Webhooks</CardTitle><CardDescription>Subscribe to publishing, content, account, engagement, and automation events.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed p-5 text-center"><Webhook className="mx-auto size-6 text-muted-foreground"/><p className="mt-2 text-sm font-semibold">No endpoints configured</p><Button variant="outline" size="sm" className="mt-4" disabled={keys.isError}>Add endpoint</Button></div></CardContent></Card></div><Card className="mt-6"><CardHeader><CardTitle>API reference</CardTitle><CardDescription>Dashboard and public endpoints share the same underlying business rules.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{["Content","Media","Schedules","Posts","Engagement","Webhooks"].map(x=><Badge key={x} variant="secondary">{x}</Badge>)}</div><Button variant="outline" className="mt-5"><Code2 className="size-4"/>Open API documentation</Button></CardContent></Card></>}
function ComingSoon({icon:Icon,title,description}:{icon:typeof Bot;title:string;description:string}){return <Card className="overflow-hidden"><CardContent className="relative grid min-h-72 place-items-center p-8 text-center"><div className="absolute inset-0 dot-grid opacity-50"/><div className="relative"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-6"/></span><Badge className="mt-4" variant="warning">Configuration required</Badge><h2 className="mt-3 font-display text-2xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{description}</p></div></CardContent></Card>}
